name: taranis
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  crossplat_objectid: ^3.0.0
  shared_preferences: ^2.0.15
  flutter_platform_widgets: ^1.20.0
  http: ^0.13.4
  html: ^0.15.0
  webview_flutter: ^3.0.0
  flutter_native_splash: any
  flutter_launcher_icons: "^0.9.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
      - family: Gordita
        fonts:
          - asset: assets/fonts/Gordita_Regular.otf
          - asset: assets/fonts/Gordita_Medium.otf
            weight: 500
          - asset: assets/fonts/Gordita_Bold.otf
            weight: 700
          - asset: assets/fonts/Gordita_Light.otf
            weight: 300
            
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/logo.png"
  android: true